
module.exports = {
    tableReleased: [//回放上传中
        {
            liveId: '111',
            index: '1',
            liveName: '第一场(已经发布)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            isTop: false,
            status: '下架',
            statusCode: '0',
            pay: '免费',
            url: 'http://www.baidu.com?keywork=1234344354654646546456456456',
        },
        {
            liveId: '222',
            index: '2',
            liveName: '第二场(已经发布)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            isTop: false,
            status: '预告',
            statusCode: '1',
            pay: '免费',
            url: 'http://www.baidu.com?keywork=afdsfdsafsadfsafsdadfdasdfs',
        },
        {
            liveId: '333',
            index: '3',
            liveName: '第三场(已经发布)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            isTop: false,
            status: '正在直播',
            statusCode: '2',
            pay: '免费',
            url: 'http://www.baidu.com?keywork=SDFSDFSDFSDFDSFDSFSADFSF',
        },
        {
            liveId: '333',
            index: '4',
            liveName: '第三场(已经发布)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            isTop: false,
            status: '中断直播',
            statusCode: '3',
            pay: '免费',
            url: 'http://www.baidu.com?keywork=SDFSDFSDFSDFDSFDSFSADFSF',
        },
        {
            liveId: '333',
            index: '5',
            liveName: '第三场(已经发布)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            isTop: false,
            status: '直播结束',
            statusCode: '4',
            pay: '免费',
            url: 'http://www.baidu.com?keywork=SDFSDFSDFSDFDSFDSFSADFSF',
        },
        {
            liveId: '333',
            index: '6',
            liveName: '第三场(已经发布)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            isTop: false,
            status: '回放',
            statusCode: '5',
            pay: '免费',
            url: 'http://www.baidu.com?keywork=SDFSDFSDFSDFDSFDSFSADFSF',
        },
        {
            liveId: '111',
            index: '1',
            liveName: '第一场(已经发布)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            isTop: false,
            status: '回放-转码中',
            statusCode: '6',
            pay: '免费',
            url: 'http://www.baidu.com?keywork=1234344354654646546456456456',
        },
        {
            liveId: '111',
            index: '1',
            liveName: '第一场(已经发布)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            isTop: false,
            status: '回放-转码失败',
            statusCode: '7',
            pay: '免费',
            url: 'http://www.baidu.com?keywork=1234344354654646546456456456',
        }
    ],
    tableDraft: [
        {
            liveName: '第一场(草稿)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            updataTime: '2016-05-03'
        },
        {
            liveName: '第二场(草稿)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            updataTime: '2016-05-03'
        },
        {
            liveName: '第三场(草稿)',
            livePrograma: '成都',
            liveRoom: '直播厅',
            when: '2016-05-03',
            date: '2016-05-03',
            updataTime: '2016-05-03'
        }
    ],
    deleteButton: {
        status: '200',
        msg: '删除成功'
    },
    setTop: {
        status: '200',
        msg: '置顶成功'
    }
}